name: Deploy Demo to Cloudflare Pages

on:
  push:
    branches:
      - main # 或者你的主分支名称
    paths:
      - 'demo/**' # 只有当 demo 文件夹有变更时才触发

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 11 # 根据你实际使用的版本

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      
      - name: Install Dependencies
        run: pnpm install

      - name: Install Dependencies
        run: pnpm install
        working-directory: demo

      - name: Build Demo
        run: pnpm build # 或者 npm run build
        working-directory: demo

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: 'your-project-name' # 在 Cloudflare Pages 后台创建的项目名
          directory: 'dist/apps/demo' # 替换为你实际的构建输出路径
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}