name: Deploy Demo to Cloudflare Pages

on:
  push:
    branches:
      - main
    paths:
      - 'demo/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 11

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      
      - name: Install Dependencies
        run: pnpm install

      - name: Install Dependencies
        run: pnpm install
        working-directory: demo

      - name: Build Demo
        run: pnpm build
        working-directory: demo

      - name: Install Wrangler
        run: pnpm add -w wrangler@3.90.0

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy demo/dist --project-name=echarts-readymade
